package zerrors

import (
	"errors"
	"github.com/samber/oops"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestTo{{ .ErrorName }}OnNil(t *testing.T) {
	err := To{{ .ErrorName }}(nil, "id")
	ok := Is{{ .ErrorName }}(err)
	assert.False(t, ok)
	assert.Equal(t, err, nil)

}

func TestTo{{ .ErrorName }}(t *testing.T) {
	err := To{{ .ErrorName }}(errors.New("not domain"), "id")
	assert.True(t, Is{{ .ErrorName }}(err))

	var e oops.OopsError
	ok := errors.As(err, &e)
	assert.True(t, ok)
	assert.Equal(t, Err{{ .ErrorName }}, e.Code())
}

func TestIs{{ .ErrorName }}OnNonDomain(t *testing.T) {
	err := errors.New("I am found!")
	ok := Is{{ .ErrorName }}(err)
	assert.False(t, ok)

}

func TestThrow{{ .ErrorName }}(t *testing.T) {
	err := Throw{{ .ErrorName }}("create", "user", "sam")
	ok := Is{{ .ErrorName }}(err)
	assert.True(t, ok)

	assert.Equal(t, err.Error(), "cannot create 'sam' of kind 'user'")
}

func Test{{ .ErrorName }}f(t *testing.T) {
	err := {{ .ErrorName }}f("something happened: %s", "reason")
	ok := Is{{ .ErrorName }}(err)
	assert.True(t, ok)

	assert.Equal(t, err.Error(), "something happened: reason")
}